# Generated by Django 5.0.7 on 2025-09-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_class_allow_herd_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='enrollment_tokens',
            field=models.IntegerField(default=5),
        ),
    ]
